version: "3"
services:
  web-gin-demo:
    networks:
      - gin-demo
    build: .
    container_name: gin-demo
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - "../:/go/src/app"
    depends_on:
      - db-gin-demo

  db-gin-demo:
    networks:
      - gin-demo
    image: postgres:12
    container_name: postgres-gin-demo
    ports:
      - "5434:5432"
    env_file: .env
    volumes:
        - db-gin-demo-data:/var/lib/postgresql/data/

volumes:
  db-gin-demo-data:

networks:
  gin-demo:
